快速编译调整：与GKI版本规则一致

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -560,12 +560,12 @@ jobs:
           CURRENT_TIME=$(date -u +"%a %b %d %H:%M:%S UTC %Y")
           echo "CURRENT_TIME=$CURRENT_TIME"
 
-          # 设置构建时间为上方的 `CURRENT_TIME` 变量
+          # 设置构建时间为上方的 `CURRENT_TIME` 变量 (5系)
           perl -pi -e "s{UTS_VERSION=\"\\\$\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $CURRENT_TIME\"}" ./common/scripts/mkcompile_h
           if [ -f "build/build.sh" ]; then
             sed -i 's/-dirty//' ./common/scripts/setlocalversion
           else
-          # 设置构建时间
+          # 设置构建时间 (6.1+)
             sed -i "s/build-timestamp = \$(or \$(KBUILD_BUILD_TIMESTAMP), \$(build-timestamp-auto))/build-timestamp = \"$CURRENT_TIME\"/" ./common/init/Makefile
           # 删除导出文件
             sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' ./common/BUILD.bazel
@@ -586,53 +586,29 @@ jobs:
             sed -i '/^CONFIG_LOCALVERSION=/ s/="\([^"]*\)"/="${{ inputs.version }}"/' ./common/arch/arm64/configs/gki_defconfig
           fi
 
-      # - name: 配置内核名称(快速构建)
-      #   if: ${{ inputs.fast }}
-      #   run: |
-      #       echo "更改为配置目录: $CONFIG..."
-      #       cd "$CONFIG"
-      #       sed -i 's/-dirty//' ./common/scripts/setlocalversion
-      #       echo "启用快速编译：设置随机字符串或指定内容"
-      #       case "${{ inputs.kernel_version }}" in
-      #             "6.1")
-      #                 echo "进入6.1 内核名称编辑"
-      #                 Android="-android14-11"
-      #                 Kversion="${Android}${{ inputs.version }}"
-      #                 if [ ! -z ${{ inputs.version }} ]; then
-      #                   echo "版本号不为空"
-      #                 else
-      #                   Android="-android14-11-g"
-      #                   Random_hash=$(cat /dev/urandom | tr -dc 'a-z0-9' | head -c 12)
-      #                   Suffix="-ab$(shuf -i 13100000-13199999 -n 1)"
-      #                   Kversion="${Android}${Random_hash}"
-      #                 fi
-      #                 echo $Kversion
-      #                 sed -i "\$s|echo \"\$res\"|echo \"$Kversion\"|" ./common/scripts/setlocalversion                  
-      #                 ;;
-      #             "6.6")
-      #                 echo "进入6.6 内核名称编辑"
-      #                 Android="-android15-8"
-      #                 Kversion="${Android}${{ inputs.version }}"
-      #                 if [ ! -z ${{ inputs.version }} ]; then
-      #                   echo "版本号不为空"
-      #                 else
-      #                   Android="-android15-8-g"
-      #                   Random_hash=$(cat /dev/urandom | tr -dc 'a-z0-9' | head -c 12)
-      #                   Suffix="-ab$(shuf -i 13200000-13299999 -n 1)-4k"
-      #                   Kversion="${Android}${Random_hash}-4k"
-      #                 fi
-      #                 echo $Kversion
-      #                 sed -i "\$s|echo \"\$res\"|echo \"$Kversion\"|" ./common/scripts/setlocalversion
-      #                 ;;
-      #             *)
-      #                 echo "Error: Unsupported kernel_version: '${{ inputs.kernel_version }}'"
-      #                 exit 1
-      #                 ;;
-      #         esac
+      - name: 配置内核名称(快速构建)
+        if: ${{ inputs.fast }}
+        run: |
+            echo "更改为配置目录: $CONFIG..."
+            cd "$CONFIG"
+            sed -i 's/-dirty//' ./common/scripts/setlocalversion
+            echo "启用快速编译：设置随机字符串"
+            case "${{ inputs.kernel_version }}" in
+                  "6.1")
+                      echo "进入6.1 内核名称编辑"
+                      sed -i '0,/^android_release=/s/\(android_release=.*\)/\1android14-11/' ./common/scripts/setlocalversion
+                      ;;
+                  "6.6")
+                      echo "进入6.6 内核名称编辑"
+                      sed -i 's/^file_localversion=.*/file_localversion=-android15-8/' ./common/scripts/setlocalversion
+                      sed -i '$s/.*/echo "${KERNELVERSION}${file_localversion}${scm_version}${config_localversion}"/' ./common/scripts/setlocalversion
+                      ;;
+                  *)
+                      echo "Error: Unsupported kernel_version: '${{ inputs.kernel_version }}'"
+                      exit 1
+                      ;;
+              esac
             
-      #         echo "KVERSION=$Kversion" >> $GITHUB_ENV
-      #         echo "查看内核名是否正确"
-      #         tail -n 3 ./common/scripts/setlocalversion
 
       - name: Build with retry
         uses: nick-fields/retry@v3
@@ -645,9 +621,9 @@ jobs:
             set -x
             cd "$CONFIG"
 
-            sed -i 's/BUILD_SYSTEM_DLKM=1/BUILD_SYSTEM_DLKM=0/' common/build.config.gki.aarch64
-            sed -i '/MODULES_ORDER=android\/gki_aarch64_modules/d' common/build.config.gki.aarch64
-            sed -i '/KMI_SYMBOL_LIST_STRICT_MODE/d' common/build.config.gki.aarch64
+            sed -i 's/BUILD_SYSTEM_DLKM=1/BUILD_SYSTEM_DLKM=0/' ./common/build.config.gki.aarch64
+            sed -i '/MODULES_ORDER=android\/gki_aarch64_modules/d' ./common/build.config.gki.aarch64
+            sed -i '/KMI_SYMBOL_LIST_STRICT_MODE/d' ./common/build.config.gki.aarch64
 
             echo "Building the kernel..."
             if [ -f "build/build.sh" ]; then
@@ -655,7 +631,6 @@ jobs:
             elif [ "${{ inputs.fast }}" != "true" ]; then
               tools/bazel build --disk_cache=/home/runner/.cache/bazel --config=fast --lto=thin //common:kernel_aarch64_dist || exit 1
             else
-              sed -i 's/-dirty//' common/scripts/setlocalversion
               case "${{ inputs.kernel_version }}" in
                   "6.1")
                       CLANG_VERSION="clang-r487747c"
