因不明原因，快速编译无版本号，故移除

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -563,6 +563,7 @@ jobs:
           # 设置构建时间为上方的 `CURRENT_TIME` 变量 (5系)
           perl -pi -e "s{UTS_VERSION=\"\\\$\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $CURRENT_TIME\"}" ./common/scripts/mkcompile_h
           if [ -f "build/build.sh" ]; then
+            echo "5系:删除dirty字符串"
             sed -i 's/-dirty//' ./common/scripts/setlocalversion
           else
           # 设置构建时间 (6.1+)
@@ -586,28 +587,28 @@ jobs:
             sed -i '/^CONFIG_LOCALVERSION=/ s/="\([^"]*\)"/="${{ inputs.version }}"/' ./common/arch/arm64/configs/gki_defconfig
           fi
 
-      - name: 配置内核名称(快速构建)
-        if: ${{ inputs.fast }}
-        run: |
-            echo "更改为配置目录: $CONFIG..."
-            cd "$CONFIG"
-            sed -i 's/-dirty//' ./common/scripts/setlocalversion
-            echo "启用快速编译：设置随机字符串"
-            case "${{ inputs.kernel_version }}" in
-                  "6.1")
-                      echo "进入6.1 内核名称编辑"
-                      sed -i '0,/^android_release=/s/\(android_release=.*\)/\1android14-11/' ./common/scripts/setlocalversion
-                      ;;
-                  "6.6")
-                      echo "进入6.6 内核名称编辑"
-                      sed -i 's/^file_localversion=.*/file_localversion=-android15-8/' ./common/scripts/setlocalversion
-                      sed -i '$s/.*/echo "${KERNELVERSION}${file_localversion}${scm_version}${config_localversion}"/' ./common/scripts/setlocalversion
-                      ;;
-                  *)
-                      echo "Error: Unsupported kernel_version: '${{ inputs.kernel_version }}'"
-                      exit 1
-                      ;;
-              esac
+      # - name: 配置内核名称(快速构建)
+      #   if: ${{ inputs.fast }}
+      #   run: |
+      #       echo "更改为配置目录: $CONFIG..."
+      #       cd "$CONFIG"
+      #       sed -i 's/-dirty//' ./common/scripts/setlocalversion
+      #       echo "启用快速编译：设置随机字符串"
+      #       case "${{ inputs.kernel_version }}" in
+      #             "6.1")
+      #                 echo "进入6.1 内核名称编辑"
+      #                 sed -i '0,/^android_release=/s/\(android_release=.*\)/\1android14-11/' ./common/scripts/setlocalversion
+      #                 ;;
+      #             "6.6")
+      #                 echo "进入6.6 内核名称编辑"
+      #                 sed -i 's/^file_localversion=.*/file_localversion=-android15-8/' ./common/scripts/setlocalversion
+      #                 sed -i '$s/.*/echo "${KERNELVERSION}${file_localversion}${scm_version}${config_localversion}"/' ./common/scripts/setlocalversion
+      #                 ;;
+      #             *)
+      #                 echo "Error: Unsupported kernel_version: '${{ inputs.kernel_version }}'"
+      #                 exit 1
+      #                 ;;
+      #         esac
             
 
       - name: Build with retry
@@ -631,6 +632,7 @@ jobs:
             elif [ "${{ inputs.fast }}" != "true" ]; then
               tools/bazel build --disk_cache=/home/runner/.cache/bazel --config=fast --lto=thin //common:kernel_aarch64_dist || exit 1
             else
+              # sed -i 's/-dirty//' ./common/scripts/setlocalversion
               case "${{ inputs.kernel_version }}" in
                   "6.1")
                       CLANG_VERSION="clang-r487747c"
